-- upgrade --
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(100) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `order` (
    `order_id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `address` VARCHAR(100) NOT NULL
) CHARACTER SET utf8mb4;
